config/routes.rb
Rails.application.routes.draw do
  get 'game-front-end', to: 'game_areas#show'

  get 'lobby', to: 'lobby_chats#show'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  root to: 'static_pages#home'

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/lobby_chats_controller.rb
class LobbyChatsController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @lobby_messages = LobbyMessage.all
  end
end

app/helpers/lobby_chats_helper.rb
module LobbyChatsHelper
end

app/views/lobby_chats/show.html.erb
<div class="header">
  <div class="team-menu"><%= link_to "Clue-Less", root_path %></div>

  <div class="channel-menu">
    <span class="channel-menu_name"><span class="channel-menu_prefix">#</span> lobby</span>
  </div>
</div>
<div class="main">
  <div class="listings">
    <div class="listings_channels">
      <h2 class="listings_header">Channels</h2>
      <ul class="channel_list">
        <li class="channel active">
          <a class="channel_name"><span><span class="prefix">#</span>CodeClue</span></a>
        </li>
        <br>
        <br>
        <li class="channel">
          <%= link_to "Enter Game", game_front_end_path, class:"btn btn-info btn-lg well gradient" %>
        </li>
      </ul>
    </div>
  </div>
  <div class="lobby_message-history" id="lobby_messages">
    <%= render @lobby_messages %>
  </div>
</div>
<div class="footer">
  <div class="user-menu">
    <span class="user-menu_profile-pic"></span><span class="user-menu_username"><%= link_to current_user.first_name, edit_user_registration_path  %></span>
    <span class="connection_status">online</span>
    <span class="logout"><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></span>
  </div>
  <div class="input-box">
    <input type="text" class="input-box_text" id="lobby_message_input"/>
  </div>