config/routes.rb
Rails.application.routes.draw do
  get 'game-front-end', to: 'game_areas#show'

  get 'lobby', to: 'lobby_chats#show'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  root to: 'static_pages#home'

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>ClueLessOnRails</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>

        <p class="notice shift"><%= notice %></p>
        <p class="alert shift"><%= alert %></p>

        <div class="nav">

          <% if current_user %>
            <%= link_to "Lobby", lobby_path %>
            <%= link_to "Profile", edit_user_registration_path %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Register", new_user_registration_path %>
            <%= link_to "Login", new_user_session_path %>
          <% end %>
          <br>
        </div>

        <div class="site-wrapper">
            <div class="site-wrapper-inner">
                <div class="cover-container">
                    <%= video_tag( 'clue-video.mp4', id: 'background', autoplay: true, loop: true, muted: true, poster: 'clue-mansion.jpg' ) %>
                    <div class="cover-container-opacity"></div>

                    <%= yield %>
                </div>
            </div>
        </div>
    </body>
</html>